markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
smalltitle: PCPM
title: Poker Club Pont-saint-martin
# Description of the Site
description: PCPM, est une association qui organise des tournois de poker √† but non-lucratif, cr√©er en 2023.
# URL of Image of the Site
site-image: /PCPM/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

presentations: 
- L‚Äôassociation Poker Club de Pont St Martin  s‚Äôest compos√©e autour de 10 personnes.
- Nous avons mont√© cette association √† partir de discussions lors de nos parties. Voil√† pr√®s de 6 ans que nous nous r√©unissons tous les mois et jouons au poker, avec r√©alisation de gros tournois occasionnels. Ces discussions ont donn√© lieu √† un nouveau pari, celui de cr√©er notre propre association √† Pont St Martin, avec organisation de 4 √† 6 tournois par an.
- L‚Äôassociation ‚ÄúP.C.P.M.‚Äù a donc √©t√© cr√©√©e en septembre 2023 et porte en son nom des valeurs que nous souhaiterions transmettre, en croisant le monde rural avec des √©v√®nements festif, conviviaux, interg√©n√©rationnel et multiculturel.

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: contact@pokerpcpm.fr
telephone: 06 01 14 02 78
facebook_username: 61555311572133
# twitter_username: 
instagram_username: pokerpcpm
# linkedin_username: thedevslot
# github_username:  thedevslot
# youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
google-analytics: RAS

# Disqus
disqus-shortname: 

# Name of the Author
author-name: PokerPCPM
# URL for the Image of the Author
author-image: https://pokerpcpm.fr/assets/images/logo_4.jpg
logo-image: https://pokerpcpm.fr/assets/images/logo_menu_pcpm.svg
team-image: assets/images/Photo_assotioation_bureau_mars_2023.svg
message-bandeau: 
  text: "üí• Cliquez ici pour vous inscrire au prochain tournoi üí•"
  lien: /blog/tournois-2025-01-26
  #svg: https://pokerpcpm.fr/assets/images/Affiche_site_22juin2024.png
mot-du-president: 
  - ‚Äò‚ÄòEnsemble, r√©alisons nos objectifs‚Äô‚Äô
  - Chers amis, en tant que pr√©sident de cette association, je suis ravi de vous annoncer la cr√©ation de PCPM. Nous, nous r√©jouissons de la force et de l‚Äô√©nergie que vous allez apporter √† notre communaut√©. Votre engagement t√©moigne de votre soutien de nos valeurs et √† participer √† notre projet associatif. Vous rejoignez une association qui est un pilier essentiel dans la vie de notre localit√©, et je suis convaincu que votre contribution sera d√©terminante pour notre avenir commun.
  - Chers partenaires, je tiens √† exprimer notre gratitude pour votre d√©vouement et votre passion. Vous serez le c≈ìur battant de notre association, la source de notre √©nergie, de notre r√©silience et de notre d√©veloppement. Sans vous, notre association ne pourrait pas accomplir sa mission. Votre travail, votre enthousiasme et votre g√©n√©rosit√© sont une source d‚Äôinspiration pour nous tous. Au nom de tous les membres, je vous adresse un grand merci.
  - Derni√®re chose, la priorit√© est l‚Äôesprit collectif, essentielle dans le monde associatif, signifiant que nous sommes tous b√©n√©voles, et que chacun peut √™tre acteur s‚Äôil le souhaite. Respect, Convivialit√©, Excellence, Responsabilit√©, Transparence, Int√©grit√© sont des valeurs qui me sont ch√®res et que je souhaite partager tous ensemble. 

# 60 Words About the Author
author-about: Site officiel du poker club de Pont-Saint-Martin
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/PineauSullivan

afficher-post-dates-bientot-disponible:
  active: False
#  message: "Prochain tournoi pr√©vu le 25/01/2025."

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
